<?php
/**
 * Frontend view for Monetivo Payment module
 *
 * @category    Monetivo
 * @package     Monetivo_Payment
 * @author      monetivo <hello@monetivo.com>
 */
/** @see Monetivo_Payment_Block_Form */
/** @var Monetivo_Payment_Block_Form $this */
?>
<ul class="form-list" id="paymen_form_<?php echo $this->getMethodCode() ?>" style="display: none;">
	<li class="form-alt">
		<?php echo $this->__('Za moment zostaniesz przekierowany do strony platnosci'); ?>
	</li>
</ul>
